### ISSUE TITLE
Logo ng-Panamá

### ISSUE THREAD

**Issue by bradleySuira** [ng-panama/origin-group#1]
Hola, agrego tres opciones para el logo para obtener sus opiniones:

**_Opción 1**_
![ngpanama_logo_1](https://cloud.githubusercontent.com/assets/1889891/7488463/47c3305a-f390-11e4-9676-e2fa337c935a.jpg)

**_Opción 2**_
![ngpanama_logo_2](https://cloud.githubusercontent.com/assets/1889891/7488465/5bada0aa-f390-11e4-9967-cf326e2ffe07.jpg)

**_Opción 3**_
![ngpanama_logo_3](https://cloud.githubusercontent.com/assets/1889891/7488469/6273c6c6-f390-11e4-85ce-1d738b858303.jpg)

**_Opción 4**_
![ngpanama_logo_4](https://cloud.githubusercontent.com/assets/1889891/7498170/79fa2a48-f3e4-11e4-8ced-66108e754fbb.jpg)

**Comment by molekilla** [comment]
#3 con p minúscula

**Comment by bradleySuira** [comment]
Agrego **_opción #4**_, yo voto por esa, si prefieres para la #3 en minúscula puedo modificarlo sin problema.

**Comment by molekilla** [comment]
@ariellindo opina

**Comment by rbonillajr** [comment]
#3 tambien

**Comment by ariellindo** [comment]
#3 for the win, por la tipografia boldy

**Comment by bradleySuira** [comment]
- Se escogió la No. 3 en la última reunión
- Se crea branch Logo con fuentes y muestras y se crea pull request
