### ISSUE TITLE
Agenda #5 - Septiembre 19 - Kotowa CdRey

### ISSUE THREAD

**Issue by molekilla** [ng-panama/origin-group#10]
# Propuestas abiertas
### Referencias
- http://blogs.msdn.com/b/typescript/archive/2015/07/20/announcing-typescript-1-5.aspx
- http://legacytotheedge.blogspot.com/2015/01/using-es6-with-your-angularjs-project.html
- https://www.npmjs.com/package/gulp-typescript
### Referencias
- Agregar fork de @bradleySuira 
- Agregar repo de @rbonillajr

**Comment by bradleySuira** [comment]
**Creating a TypeScript Workflow with Gulp:** [dwahlin Post](http://weblogs.asp.net/dwahlin/creating-a-typescript-workflow-with-gulp)

**Comment by molekilla** [comment]
este es mejor
https://angular.io/docs/js/latest/quickstart.html

**Comment by molekilla** [comment]
este corre con typescript y systemjs

https://github.com/molekilla/rutha/tree/ts_systemjs

cons
- imposible usar import angular from 'angular'
- quiero usar templateCache

pros
- Bower !
