### ISSUE TITLE
Agenda - 2da Reunión

### ISSUE THREAD

**Issue by bradleySuira** [ng-panama/origin-group#2]
Posibles temas para la 2da reunión (propuestos hasta ahora)
- Mobile con ng
- Nuestro feedback de Kendo grids
- news (angular 2.0, ES6, ...)
- latamjs
- Seguridad en SPA’s.
- Estructura de directorios y archivos en aplicaciones con angulares (https://github.com/johnpapa/angular-styleguide).
- Server side rendering vs client side rendering, pros y contras.
- NativeScript presentado por René Bonilla.
- TypeScript

Propongo escoger solo algunos de estos temas (3 o 4 máximo).

**Comment by molekilla** [comment]
Mobile, kendo y native mi votación

**Comment by bradleySuira** [comment]
Voto por Native o TypeScript, Mobile y compartir sobre noticias news (angular 2.0, ES6, ...)

**Comment by rbonillajr** [comment]
Native usando telerik platform
