### ISSUE TITLE
Agenda - 3ra Reunion

### ISSUE THREAD

**Issue by edgarSucre** [ng-panama/origin-group#3]
No hay muchas news así que podemos hacer un mix de temas.

Propongo:
- Discusión de module bundlers (browserify, webpack, jspm).
- Ionic
- Angular 1.4
- Cuando el nuevo router?

**Comment by bradleySuira** [comment]
Propongo JWT y Token refresh

**Comment by oidacra** [comment]
Buenas soy nuevo viendo esto, cuando se reúnen nuevamente?.

**Comment by molekilla** [comment]
queremos la 4ta entrega mid July ? Que opinas, la organizamos un 16 a las
6.30 pm ? Edgar, B, Rene, Ariel ?

**Comment by oidacra** [comment]
Por mi perfecto. Allí estaré.

Saludos.

**Comment by bradleySuira** [comment]
Hola por mi está ok y pues la última vez quedé mal así que solo me dicen el lugar y hora y yo llego.

Saludos

**Comment by rbonillajr** [comment]
Listo yo envio la agenda @oidacra me das tu mail para agregarte.

Dia 16 de Julio 2015 Hora: 6 p.m.

Lugares para que boten:
- Friday Dorado en la terraza (este es bueno hay medio precio)
- Casa Diabla via españa (en el area con aire)
- Se acepta propuesta

**Comment by bradleySuira** [comment]
Friday +1

**Comment by rbonillajr** [comment]
Entre los temas les hablare del siguiente reto a ver que les parece si hacemos un evento a pequeña escala de angular donde presentaremos el grupo y hablaremos que es angular, como adoptarlo, con que convive, quien lo utiliza en Panamá, etc.

seria genial hacer un evento al año. si planificamos creo podemos hacer uno a final de este año o inicio del otro.

Estoy pilando ng2 para presentarlo si la idea se da. Les hablare un poco de esto en la próxima reunión.

**Comment by oidacra** [comment]
mi correo es arcadio@accionasolutions.net
