### ISSUE TITLE
Agenda reunion 22 Agosto

### ISSUE THREAD

**Issue by edgarSucre** [ng-panama/origin-group#9]
Puntos a discutir:
- Browserify vs requirejs vs webpack etc.
- I18n
- Frameworks rest es6
- Gulp 4

**Comment by molekilla** [comment]
@edgarSucre @bradleySuira @rbonillajr http://www.meetup.com/es/PanamaDotNet/events/223962171/

Algo que me gusta de ese grupo... es que no es gratis y asisten !!! Como lo replicamos ?

**Comment by bradleySuira** [comment]
Pienso que - se puede buscar un lugar fijo ( es complicado pero se puede ver). Llevaría
todo más logística y tiempo a invertir por todos. - Hay personas reconocidas y muy buenas en lo que hacen en este grupo creo que
eso ayudaría a promocionar. - No necesariamente debe ser algo para generar una gran cantidad de ingresos
pero podría catapultar otras cosas, por ejemplo si escribimos, un blog,
tutoriales, tips, etc, eso haria ver el grupo como grandes conocedores,
acumularías seguidores, etc y asi veran como de gran valor asistir para aprender
u obtener tips y escuchar experiencias y errores vividos. - El site build by ng- panama ( que por cierto no he hecho nada sobre eso, mis
disculpas pero ando full)
No se si lo que digo va acorde a lo que quieres, lo que comento va mas
encaminado a atraer gente con menos expertis, gente nueva que quiere iniciarse
con angular o quisieras en lugar de eso atraer a mas desarrolladores expertos ?
Saludos

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.4.7&pv=8.3]
On Sat, Aug 15, 2015 at 11:13 AM, Rogelio Morrell notifications@github.com
wrote:
@edgarSucre [https://github.com/edgarSucre] @bradleySuira [https://github.com/bradleySuira] @rbonillajr [https://github.com/rbonillajr] http://www.meetup.com/es/PanamaDotNet/events/223962171/
[http://www.meetup.com/es/PanamaDotNet/events/223962171/]

Algo que me gusta de ese grupo... es que no es gratis y asisten !!! Como lo
replicamos ?

—
Reply to this email directly or view it on GitHub
[https://github.com/ng-panama/origin-group/issues/9#issuecomment-131396811] .[https://github.com/notifications/beacon/ABzWY_y5tt3SNgtxXbmAuclim1kQaZdlks5on1yRgaJpZM4FsBfA.gif]

**Comment by molekilla** [comment]
@bradleySuira recuerda enviarme el fork de @molekilla/rutha-ionic
@edgarSucre recuerda lo de TS

**Comment by bradleySuira** [comment]
@molekilla te hice el fork [https://github.com/bradleySuira/rutha-ionic](https://github.com/bradleySuira/rutha-ionic) pero me da problemas al tratar de ejecutar algún task, me dice que faltan algunos módulos pero al ejecutar npm install me dice que no hay nada pendiente por instalar
